version: "3.7"

services:

  #############################################################################
  # tranSMART Postgres database
  #############################################################################
  db:
    image: lukaszimmermann/transmart-core-thehyve-postgres_test:v1
    ports:
      - ${databaseHostPort}:5432 # Makes Postgres available to the outside world

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - ${adminerHostPort}:8080

  # keycloak:
  #   image: jboss/keycloak:5.0.0
  #   environment:
  #     KEYCLOAK_USER: admin
  #     KEYCLOAK_PASSWORD: admin
  #     DB_VENDOR: postgres
  #     DB_ADDR: db
  #     DB_PORT: 5432
  #     DB_DATABASE: keycloak # This is the default of the image
  #     DB_USER: keycloak # This is the default of the image
  #     DB_PASSWORD: password # This is the default
  #
  #
  # solr:
  #   image: guywithnose/solr:4.5.1
  #   ports:
  #     - ${solrHostPort}:8983

  transmart-server:
    image: lukaszimmermann/transmart-core-thehyve-server:v1
    depends_on:
      - db
    environment:
      PGHOST: db
      PGPORT: 5432
    ports:
       - 8080:8080
